networks:
  interal:
    driver: bridge

volumes:
  postgres-data:

services:
  #java-service:
  #context: ./
   #   dockerfile: Dockerfile
    
  #  depends_on:
  #    - postgres-db

   # container_name: java-app

   # ports:
   #   - 8080:8080

  #  networks:
  #    - interal
      
  postgres-db:
    image: postgres:17.6-alpine3.22
    restart: unless-stopped

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=q1w2e3r4t5y6u7i8o9p0
      - POSTGRES_DB=postgres
      - PGPORT=8090

    volumes:
      - postgres-data:/var/lib/postgresql/data

    ports:
      - 8090:8090

    networks:
      - interal

  pg-admin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: q1w2e3r4t5y6u7i8o9p0
      PGADMIN_LISTEN_PORT: 8088
    
    ports:
      - 8088:8088
    
    depends_on:
      - postgres-db

    networks:
      - interal